name: FreezeFire-Freebuild
version: '${project.version}'
main: de.arealzenix.freebuild.FreeBuild
api-version: 1.18
authors: [ ARealZenix, Chaos ]

depend:
  - ServerAPI

commands:
  fly:
    permission: freebuild.fly
    permission-message: ""
  setspawn:
    permission-message: ""
    permission: freebuild.admin
  spawn: